# POST  http://localhost:3000/api/auth 
# Content-Type: application/json
# {
#     "username":"ram01",
#     "password":"32jdww"
# }

@base_url = http://localhost:3000

##-> to use this to login -.> "username": "Tayle_90", "password": "123321"
#     "username": "Parroton_20071"    "password": "IashPWQss"
### Register a new user
POST {{base_url}}/api/auth/register
Content-Type: application/json

{
    "username": "Tayle_90",
    "password": "123321"
}
###
POST {{base_url}}/api/auth/register
Content-Type: application/json

{
    "username": "Parroton_20071",
    "password": "IashPWQss"
}
### logining with correct details
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "username": "Tayle_90",
    "password": "123321"
}

###

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "username": "Parroton_20071",
    "password": "IashPWQss"
}


### logining with incorrect details

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "username": "ram012",
    "password": "32jdww2"
}

####

POST {{base_url}}/api/auth/logout
Content-Type: application/json

{
    "username": "ram01",
    "password": "32jdww2"
}


###

GET {{base_url}}/api/profile/ram01

###

GET {{base_url}}/api/profile/usern11

###

GET  {{base_url}}/api/profile/all

###

DELETE {{base_url}}/api/profile/ram01 

###
POST {{base_url}}/api/profile/create
Content-Type: application/json

{
    "userid": "Tayle_90",
    "biotext": "New profile added"
}

###

POST {{base_url}}/api/profile/create
Content-Type: application/json

{
    "userid": "ram0231",
    "biotext": "HELLO welcome to my profile"
}

###
PUT {{base_url}}/api/profile/ram01 
Content-Type: application/json

{
    "bio":"hello my name is xyz"
}


###

POST {{base_url}}/api/posts/
Content-Type: application/json

{
    "userId":"Tayle_90",
    "content":"YOU are tall"
}

###

POST {{base_url}}/api/posts/
Content-Type: application/json

{
    "userId":"Aron_2001",
    "content":"YOU are tall"
}

###

POST {{base_url}}/api/posts/
Content-Type: application/json

{
    "userId":"Tayle_90",
    "content":"Good night ,Sweet Dreams :)"
}

###
GET {{base_url}}/api/posts/














# POST {{base_url}}/api/profile/create
# Content-Type: application/json
//idhr space hona jruri hai
# {
#     "userid": "aasjsjdsjsssss",
#     "biotext": "hello i am a devil"
# }


//sapcing enter ka dhyaan rkho
# if like this -> {  "message": "Profile validation failed: user: Path `user` is required."}
# POST {{base_url}}/api/profile/create

# Content-Type: application/json

# {
#     "userid": "user 32",
#     "biotext": "hello i am a devil"
# }